### ISSUE TITLE
Piwik / Matomo Tracking via traffic.okfn.de

### ISSUE THREAD

**Issue by stefanw** [dmedak/verfassungsschutzberichte.de#8]
Recent BGH rules have made it clear that cookie-based analytics need consent.

Please [disable tracking cookies](https://matomo.org/faq/general/faq_157/) and link to our [Datenschutzerklärung](https://okfn.de/impressum/#datenschutzerkl%C3%A4rung). Alternatively, please remove the tracking code.

**Comment by jfilter** [comment]
No, it's only applies for advertising. 

https://netzpolitik.org/2020/werbetreibende-duerfen-nutzerinnen-keine-tracking-cookies-unterjubeln/

**Comment by jfilter** [comment]
After further discussions and considerations, I will disable the cookies. Stats about visitors will hardly be affected. IMO the court decision does not apply here but respecting the privacy of the users is always a good idea. ;)
